name: ✅ Task
description: Create a new Task
title: "✅ Task: [Title]"
#labels: [task]
body:
  - type: textarea
    id: task-description
    attributes:
      label: Task Description
      description: "Provide a detailed description of the task."
      placeholder: "Describe the task..."
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: "List the acceptance criteria for this task."
      placeholder: "Enter acceptance criteria..."
  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: "Additional notes if any"
      placeholder: "Enter additional notes..."
