name: 🔧 Refactoring
description: Create a new Refactoring task
title: "🔧 Refactoring: [Title]"
labels: [refactoring]
body:
  - type: textarea
    id: refactoring-objective
    attributes:
      label: Refactoring Objective
      description: "Explain the goal of this refactoring."
      placeholder: "Describe the refactoring objective"
  - type: textarea
    id: code-areas-affected
    attributes:
      label: "Code Areas Affected"
      description: "List the parts of the codebase that will be affected"
      placeholder: "Explain or link existing parts"
  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: "Explain the benefits of the refactoring"
      placeholder: "Enter the benefits of the addjustments ..."
  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: "Additional notes if any"
      placeholder: "Enter additional notes..."    
