name: 🚀 Release
description: Create a new Release
title: "🚀 Release: [Version]"
labels: [release]
body:
  - type: markdown
    attributes:
      value: "## Release Overview\nProvide an overview of what this release includes."
  - type: textarea
    id: release-overview
    attributes:
      label: Release Overview
      description: "Provide a brief description of this release."
      placeholder: "Describe the key features and improvements in this release..."
    validations:
      required: true
  - type: textarea
    id: release-notes
    attributes:
      label: Release Notes
      description: "Detailed notes for this release. Include new features, improvements, bug fixes, and any breaking changes."
      placeholder: "List the release notes here...\n\nFeatures:\n- Feature 1\n- Feature"
  - type: textarea
    id: versions
    attributes:
      label: Versions
      description: "Versions of several Services"
      placeholder: "- OIDC Provider:\n- Consumer Web Frontend:\n- Backend UI:\n- GraphQL Gateway:\n- GraphQL Services:\n\n *additional services should be added also*"
  - type: textarea
    id: additional-adjustments
    attributes:
      label: Notes
      description: "Additional addjustments"
      placeholder: "Enter additional informations..."
  - type: textarea
    id: testing
    attributes:
      label: Testing
      description: "Things that we have to test, that new features are working"
      placeholder: "1. Go to ...\n 2. Click somthing ...\b 3. Expected"
